# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exporter.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xporter.proto\x12\x08\x65xporter\"5\n\rExportRequest\x12\x0f\n\x07md_path\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_path\x18\x02 \x01(\t\"\"\n\x0e\x45xportResponse\x12\x10\n\x08pdf_path\x18\x01 \x01(\t2M\n\x0bPdfExporter\x12>\n\tExportPdf\x12\x17.exporter.ExportRequest\x1a\x18.exporter.ExportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exporter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPORTREQUEST']._serialized_start=28
  _globals['_EXPORTREQUEST']._serialized_end=81
  _globals['_EXPORTRESPONSE']._serialized_start=83
  _globals['_EXPORTRESPONSE']._serialized_end=117
  _globals['_PDFEXPORTER']._serialized_start=119
  _globals['_PDFEXPORTER']._serialized_end=196
# @@protoc_insertion_point(module_scope)
